services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

  frontend:
    build:
      context: frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:80"

  mcp_server:
    build:
      context: .
      dockerfile: docker/mcp_server/Dockerfile
