import { useMemo } from 'react'
import {
    ComposedChart,
    Area,
    Scatter,
    XAxis,
    YAxis,
    Tooltip,
    CartesianGrid,
    ResponsiveContainer,
    ReferenceLine,
} from 'recharts'

import type { AxisDistributionDto } from '@/api/dto/concepts'
import { computeDensity } from '../lib/density'
import type { DensityBucket } from '../lib/density'

const GRADIENT_ID = 'densityRidgeFill'
const GLOW_FILTER_ID = 'densityRidgeGlow'

interface TooltipPayloadEntry {
    payload: DensityBucket
}

interface CustomTooltipProps {
    active?: boolean
    payload?: TooltipPayloadEntry[]
}

function CustomTooltip({ active, payload }: CustomTooltipProps) {
    if (!active || !payload?.length) return null
    const p = payload[0].payload
    return (
        <div className="rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-2.5 py-1.5 text-xs shadow-md">
            <p className="font-medium leading-snug">{p.title}</p>
            <p className="text-[var(--color-muted)] mt-0.5">≈{p.count} film{p.count !== 1 ? 's' : ''} near this score</p>
        </div>
    )
}

interface DensityRidgeProps {
    data: AxisDistributionDto
}

/**
 * Density-ridge plot of movie scores along a concept's linear axis.
 *
 * Scores are bucketed into equal-width bins across [-1, 1]. Each bucket
 * renders as one dot on a filled area ridge whose height encodes the number
 * of movies in that bin, giving a visual distribution function (the "alone" /
 * halo effect requested).
 *
 * Pole labels (generated by the concept agent) appear at the two axis extremes.
 *
 * @param data - Axis distribution with concept name, pole labels, and per-movie scored points.
 */
export function DensityRidge({ data }: DensityRidgeProps) {
    const buckets = useMemo(() => computeDensity(data.points), [data.points])

    if (buckets.length === 0) {
        return (
            <div className="flex items-center justify-center h-40 text-sm text-[var(--color-muted)]">
                No scores available.
            </div>
        )
    }

    const maxCount = Math.max(...buckets.map((b) => b.count))
    const yDomain = [0, maxCount * 1.2]

    const negativeLabel = data.negative_label || `less ${data.concept_name}`
    const positiveLabel = data.positive_label || `more ${data.concept_name}`

    return (
        <div className="w-full">
            <div className="flex justify-between text-xs text-[var(--color-muted)] px-8 mb-1 select-none">
                <span>◀ {negativeLabel}</span>
                <span>{positiveLabel} ▶</span>
            </div>
            <ResponsiveContainer width="100%" height={180}>
                <ComposedChart data={buckets} margin={{ top: 8, right: 24, bottom: 8, left: 24 }}>
                    <defs>
                        <linearGradient id={GRADIENT_ID} x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="var(--color-accent)" stopOpacity={0.55} />
                            <stop offset="95%" stopColor="var(--color-accent)" stopOpacity={0} />
                        </linearGradient>
                        <filter id={GLOW_FILTER_ID} x="-20%" y="-40%" width="140%" height="180%">
                            <feGaussianBlur in="SourceGraphic" stdDeviation="3" result="blur" />
                            <feComposite in="SourceGraphic" in2="blur" operator="over" />
                        </filter>
                    </defs>

                    <CartesianGrid
                        strokeDasharray="4 4"
                        stroke="var(--color-border)"
                        strokeOpacity={0.45}
                        vertical={true}
                        horizontal={true}
                    />

                    <XAxis
                        dataKey="x"
                        type="number"
                        domain={[-1, 1]}
                        tickCount={5}
                        tick={{ fontSize: 10 }}
                        tickLine={false}
                        axisLine={{ stroke: 'var(--color-border)' }}
                    />
                    <YAxis
                        dataKey="count"
                        type="number"
                        domain={yDomain}
                        hide
                    />

                    <ReferenceLine x={0} stroke="var(--color-border)" strokeDasharray="4 4" />

                    <Area
                        dataKey="count"
                        type="monotone"
                        fill={`url(#${GRADIENT_ID})`}
                        stroke="var(--color-accent)"
                        strokeWidth={2}
                        strokeOpacity={0.9}
                        filter={`url(#${GLOW_FILTER_ID})`}
                        dot={false}
                        activeDot={false}
                        isAnimationActive={false}
                    />

                    <Scatter
                        dataKey="count"
                        fill="var(--color-accent)"
                        opacity={0.85}
                        r={3}
                        isAnimationActive={false}
                    />

                    <Tooltip content={<CustomTooltip />} cursor={false} />
                </ComposedChart>
            </ResponsiveContainer>
        </div>
    )
}
